services:
  db:
    image: postgres:14-alpine
    restart: always
    ports: ["5432:5432"]
    volumes:
      - /home/arash/docker-volumes/typewar/pgdata:/var/lib/postgresql/data

    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: typewar
